title = "Niche Analytics: Sports Data and Analytics for Every Niche"
baseURL = "https://nicheanalytics.org/"
tags = ["sports", "analytics", "data"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
  tagline = "Moneyball for All"
  author = "Jonathan Kent"
  description = "Sports data and analytics for any niche sport and league, no matter the level. It's Moneyball for all."
  logoBig = "/images/niche_logo.png"
  logoSmall = "/images/niche_logo.png"
  favicon = "na_logo.ico"
  opengraphImage = "/images/na_logo.png"
  email = ""
  googleTagManger = ""
  customCSS = true

  # Social media links in footer
  #twitter = "TomaNistor"
  #linkedin = "tomanistor"
  #github = "tomanistor"
  #facebook = ""

  # Copyright and theme author credit in footer
  copyright = true
  credit = false

  # Cache busting of static resources (additional set up required)
  cacheBustCSS = false
  cacheBustJS = false

  # Code highlighting with highlight.js
  highlightJS = true
  highlightJSStyle = "" # For custom highlight.js styles, add your /path/to/styles/default.css
  highlightJSScript = "" # For custom highlight.js languages config, add your /path/to/highlight.pack.js

  # Choose either Formspree contact form or Basin contact form
  ajaxFormspree = false
  ajaxFormspreeGold = false
  ajaxBasin = "https://usebasin.com/f/73643ba55784"

  # Lazy loading with lazysizes
  lazyloading = true

[[menu.main]]
  name = "About"
  url  = "/#about"
  weight = 1
[[menu.main]]
  name = "Projects"
  url  = "/#projects"
  weight = 2
[[menu.main]]
  name = "Contact"
  url  = "/#contact"
  weight = 3
